/**
* @file AddEdgeDialog.h
 * @brief Dialog window for adding a new edge to the graph.
 */

#pragma once
#include <QDialog>

QT_BEGIN_NAMESPACE
namespace Ui { class AddEdgeDialog; }
QT_END_NAMESPACE

/**
 * @brief Dialog window class for adding a new edge to the graph via GUI.
 */
class AddEdgeDialog : public QDialog {
    Q_OBJECT
public:
    /**
     * @brief Constructs an AddEdgeDialog.
     * @param weighted Indicates whether the graph is weighted to show/hide the weight input field.
     * @param maxVertexId The highest available vertex ID to set boundaries for the spin boxes.
     * @param parent Pointer to the parent widget.
     */
    explicit AddEdgeDialog(bool weighted, int maxVertexId, QWidget* parent = nullptr);

    /**
     * @brief Destructor.
     */
    ~AddEdgeDialog() override;

    /**
     * @brief Gets the selected source vertex ID.
     * @return The ID of the origin vertex.
     */
    int getFromId() const;

    /**
     * @brief Gets the selected destination vertex ID.
     * @return The ID of the target vertex.
     */
    int getToId() const;

    /**
     * @brief Gets the input weight for the edge.
     * @return The edge weight value.
     */
    double getWeight() const;

private:
    Ui::AddEdgeDialog* ui; ///< Pointer to the UI components generated by Qt Designer.
};