/**
* @file ControlPanel.h
 * @brief GUI component providing controls for interacting with the graph and algorithms.
 */

#pragma once
#include <QWidget>
#include <vector>
#include <QString>
#include "AlgorithmController.h"
#include "Vertex.h"

QT_BEGIN_NAMESPACE
class QPushButton;
namespace Ui { class ControlPanel; }
QT_END_NAMESPACE

/**
 * @brief The ControlPanel class manages the graphical user interface controls
 * for graph editing, algorithm execution, and graph visualization exporting.
 */
class ControlPanel : public QWidget {
    Q_OBJECT
public:
    /**
     * @brief Constructs the ControlPanel widget.
     * @param parent Pointer to the parent widget.
     */
    explicit ControlPanel(QWidget* parent = nullptr);

    /**
     * @brief Destructor.
     */
    ~ControlPanel() override;

    /**
     * @brief Enables or disables the graph editing tools (add/remove vertices and edges).
     * @param enabled True to enable, false to disable.
     */
    void setGraphEditingEnabled(bool enabled);

    /**
     * @brief Enables or disables the algorithm playback controls.
     * @param enabled True to enable, false to disable.
     */
    void setAlgorithmControlsEnabled(bool enabled);

    /**
     * @brief Enables or disables the graph export functionality.
     * @param enabled True to enable, false to disable.
     */
    void setExportEnabled(bool enabled);

    /**
     * @brief Updates the combo boxes used for selecting start and end vertices.
     * @param vertices A list of available active vertices to populate the boxes.
     */
    void updateStartVertexComboBox(const std::vector<const Core::Vertex*>& vertices);

    /**
     * @brief Resets the algorithm player control buttons to their initial state.
     */
    void resetPlayerControls();

    /** @name Control Buttons Getters */
    ///@{
    QPushButton* getNextButton() const;
    QPushButton* getPrevButton() const;
    QPushButton* getPlayButton() const;
    QPushButton* getPauseButton() const;
    QPushButton* getStartButton() const;
    ///@}

signals:
    /** @name Custom Signals */
    ///@{
    void startAlgorithmClicked(int startId, int endId);
    void pauseAlgorithmClicked();
    void playAlgorithmClicked();
    void speedChanged(int speed);
    void resetClicked();
    void nextClicked();
    void prevClicked();
    void algorithmChanged(Algorithms::AlgorithmType type);
    void setupGraphButtonClicked();
    void addVertexClicked();
    void addEdgeClicked();
    void removeVertexClicked();
    void removeEdgeClicked();
    void applyLayoutClicked();
    void exportClicked(const QString& format);
    void chooseDirClicked();
    ///@}

private slots:
    /** @name Internal UI Event Slots */
    ///@{
    void onStartAlgorithmClicked();
    void onPauseAlgorithmClicked();
    void onPlayAlgorithmClicked();
    void onSpeedSliderChanged(int value);
    void onResetClicked();
    void onAlgorithmChanged(int index);
    void onExportClicked();
    ///@}

private:
    Ui::ControlPanel* ui; ///< Pointer to the UI components generated by Qt Designer.
};