/**
* @file GraphSetupDialog.h
 * @briefgraphics Dialog window for configuring initial graph parameters.
 */

#pragma once
#include <QDialog>
#include <vector>
#include <tuple>

/**
 * @brief Structure containing basic global configuration settings for the graph.
 */
struct GraphSettings {
    bool directed; ///< True if the graph edges are directed.
    bool weighted; ///< True if the graph edges contain numerical weights.
};

QT_BEGIN_NAMESPACE
namespace Ui { class GraphSetupDialog; }
QT_END_NAMESPACE

/**
 * @brief Dialog window for the initial setup of a new graph.
 * * Allows the user to specify whether the graph is directed or weighted,
 * the total initial vertex count, and a custom list of pre-configured edges.
 */
class GraphSetupDialog : public QDialog {
    Q_OBJECT
public:
    /**
     * @brief Constructs a GraphSetupDialog.
     * @param parent Pointer to the parent widget.
     */
    explicit GraphSetupDialog(QWidget* parent = nullptr);

    /**
     * @brief Destructor.
     */
    ~GraphSetupDialog() override;

    /**
     * @brief Retrieves the basic directed and weighted settings specified by the user.
     * @return The populated GraphSettings struct.
     */
    GraphSettings getSettings() const;

    /**
     * @brief Retrieves the number of vertices the user wishes to create initially.
     * @return The vertex count as an integer.
     */
    int getVertexCount() const;

    /**
     * @brief Parses and retrieves the user-provided initial edges.
     * @return A vector of tuples containing (Source ID, Destination ID, Weight).
     */
    std::vector<std::tuple<int, int, double>> getEdges() const;

private:
    Ui::GraphSetupDialog* ui; ///< Pointer to the UI components generated by Qt Designer.
};